name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH access for deployment
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Step 3: Deploy and manage code on EC2
      - name: Deploy to EC2
        run: |
          ssh -i “/Users/shara/Documents/aws_key/netflix_key.pem” ubuntu@3.84.41.200 << 'EOF'
            # Ensure the repo is present or clone it
            if [ ! -d "/home/ubuntu/docker-todo" ]; then
              git clone https://github.com/Shara2922/docker-todo.git /home/ubuntu/docker-todo
            fi

            # Always pull the latest code before proceeding
            cd /home/ubuntu/docker-todo
            export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa"
            git pull origin main

            # Ensure Docker permissions are correct
            sudo usermod -aG docker ubuntu

            # Rebuild the Docker image with the latest changes
            sudo docker build -t todo-list-app .

            # Stop and remove any existing container
            sudo docker rm -f todo-list-app || true

            # Run the new container with updated code
            sudo docker run -d -p 80:3000 --name todo-list-app todo-list-app
          EOF